### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by Wangxuecheng666** [jchengai/forecast-mae#1]
Thanks for your great work.
The visualization you made is excellent, could you share how it was achieved? Could you share the code of the visualization? Thank you!

**Comment by jchengai** [comment]
Thanks for your interest in our work, I will clean and share the visualization part soon.

**Comment by jchengai** [comment]
Please refer to https://github.com/jchengai/forecast-mae/blob/main/notebook/visualization.ipynb.

**Comment by Wangxuecheng666** [comment]
Thank you very much.

从 Windows 版邮件发送

发件人: Jie Cheng
发送时间: 2023年9月4日 9:59
收件人: jchengai/forecast-mae
抄送: Wangxuecheng666; Author
主题: Re: [jchengai/forecast-mae] visualization (Issue #1)

Thanks for your interest in our work, I will clean and share the visualization part soon.
