### ISSUE TITLE
ensemble code

### ISSUE THREAD

**Issue by LL-C8** [jchengai/forecast-mae#10]
Hi!
Can you provide the experimental code for Ensemble?

**Comment by jchengai** [comment]
Hi, @LL-C8. We use k-means for endpoint clustering and linearly re-scale the probability. I think the implementation is quite straightforward.

**Comment by LL-C8** [comment]
> Hi, @LL-C8. We use k-means for endpoint clustering and linearly re-scale the probability. I think the implementation is quite straightforward.
Could you please provide me with the combinations of learning_rate and attention radius that you selected when choosing the submodels? Thank you!
