### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by liuscot** [jchengai/forecast-mae#11]
![截图 2024-01-10 10-00-04](https://github.com/jchengai/forecast-mae/assets/129735290/7472c5af-4e69-4de3-8604-032f1decabce)

Are you sure that trainer_mae is importable from module src.model ? 
This problem arises.

**Comment by liuscot** [comment]
The problem was solved because the natten package was not installed. I installed it according to  sh ./scripts/setup.sh. I don’t know why it was not installed. Then I went to the official website to install it successfully.

**Comment by hamza-abuzahra** [comment]
what version of natten did you install?
when running the setup.sh, it tires to download 0.14.2, but it gives an error saying 'no matching distribution found for natten==0.14.2'
i have tried with various other versions, but the build keeps failing for some reason
