### ISSUE TITLE
Preprocessing code for Argoverse 1 dataset

### ISSUE THREAD

**Issue by Ross-Stein** [jchengai/forecast-mae#12]
Hello Jie @jchengai,

First I would like to thank you for such good work again! :)

We are currently exploring deeper with your code, and find your framework has great potential.

Also, we saw some results for AV1 and WOMD in your supplementary materials. 

Could you please also share the preprocessing code for Argoverse 1? 
We want to check the performance of our work on AV1 as well, based on your code.

Thanks for your help!
BTW, HAPPY Chinese New Year to you and your team!

Best,
Ross

**Comment by LL-C8** [comment]
> Hello Jie @jchengai,
> 
> First I would like to thank you for such good work again! :)
> 
> We are currently exploring deeper with your code, and find your framework has great potential.
> 
> Also, we saw some results for AV1 and WOMD in your supplementary materials.
> 
> Could you please also share the preprocessing code for Argoverse 1? We want to check the performance of our work on AV1 as well, based on your code.
> 
> Thanks for your help! BTW, HAPPY Chinese New Year to you and your team!
> 
> Best, Ross
Hello, I am also doing research on this. 
Have you obtained the preprocessing code for the AV1 dataset and WOMD?
Could you please share the preprocessing code for AV1 and WOMD?

Thanks for your help!

**Comment by penglo** [comment]
Hi Ross,

I noticed that you are also looking for the preprocessing code for AV1 in forecast-mae. Have you found it yet? If so, could you please share it? I would greatly appreciate it!

Best,
Penglong Li
