### ISSUE TITLE
About the length of data

### ISSUE THREAD

**Issue by gankaia** [jchengai/forecast-mae#14]
Hi! Thanks for your wonderful work first!
When I try to reproduce your code, I find that in the preprocessed data, _x_ takes the data of the first 50 time steps, and _y_ is after 50, but many of the original data are 0-49 in length, so _y_ is empty, does the true value of y still exist?

**Comment by jchengai** [comment]
Hi, @kelen1, the regression mask is used to prevent the problem you mentioned during the training

https://github.com/jchengai/forecast-mae/blob/cb86ea92601d23a8af7713389e9fb78d7e546a65/src/model/trainer_forecast.py#L89-L91

**Comment by gankaia** [comment]
Thanks!
