### ISSUE TITLE
Av2 Multi Agents Forecasting

### ISSUE THREAD

**Issue by Ross-Stein** [jchengai/forecast-mae#2]
Hi @jchengai ,

Firstly, we'd like to express our gratitude for your outstanding work!

We are also interested in the field of multi-agent forecasting. 
Do you have any plans to release the training and testing/submission code for multi-agent forecasting (especially on the av2 dataset) in the future? Access to the code would be also precious for us.

Could you please let us know if you have any thoughts or a potential timeline for releasing the code? 
We're eager to further explore your work.

Thanks for your time and contributions. :)

Best regards,
Ross

**Comment by jchengai** [comment]
Hi Ross,  thank you for your interest in our work. The multi-agent version incorporates several modifications compared to the current one:

- We center the scene around the autonomous vehicle.
- We employ a ViT-like CLS token to compute scores for each potential scene.

Yes, I would like to provide an exemplary pipeline for multi-agent forecasting (on AV2) if it is beneficial to the community. While I cannot commit to a specific timeline, there is a high likelihood that it will be available within this month :).

**Comment by Ross-Stein** [comment]
Hi Jie, 

thank you for the detailed explanation about the modifications of the multi-agent version!  

Also, very happy to hear that you are about to share the code, It would be another great contribution. :)
Looking forward to accessing it, thanks! 

Best,
Ross

**Comment by jchengai** [comment]
Hi, @Ross-Stein, an multiagent baseline model is now released (performance and checkpoints will be updated once I finish the training). I hope it helps :).  

p.s. please note that it's a close one, but not the leaderboard version.

**Comment by Ross-Stein** [comment]
Hi Jie @jchengai ,

Thanks for your baseline model, It is incredibly useful! :)
We're eagerly looking forward to starting the training process.

Warm regards,
Ross
