### ISSUE TITLE
Probabilities for all agents in multi-agent forecasting

### ISSUE THREAD

**Issue by KexianShen** [jchengai/forecast-mae#5]
Great work.

I have a question on the probabilities for the trajectory in multi-agent forecasting. Why is probability (pi) with size of (B, K) instead of (B, K, N) like trajectory which is (B, K, N, 60, 2)?

**Comment by jchengai** [comment]
Hi, @KexianShen. It's modelled as a joint prediction task (as required by the benchmark) where the probability is evaluated at the scene level. (B, K, N) is the marginal prediction case where each agent may have different probability for each mode.

**Comment by jchengai** [comment]
Well, it is possible to merge the marginal probability through post-processing tricks such as sorting, averaging et al. and see which one is better through local validation.  

However, I'm not sure whether it is worthy spending time on this, as it does not make much sense in principle. Joint modeling and training seems to be a more interesting direction.

**Comment by KexianShen** [comment]
hi, @jchengai. I uploaded the submission to eval.ai, and it seems being sticking at "submitted" status. Have you encountered this situation before?
