### ISSUE TITLE
MAE Pre-Training Weights

### ISSUE THREAD

**Issue by a-pru** [jchengai/forecast-mae#7]
Hi,

Could you possible provide the checkpoint of the MAE model after pre-training? Really appreciate your work!

Thanks.

Best,
Alex

**Comment by jchengai** [comment]
Hi @a-pru, the mae ckpt  is updated to the [README](https://github.com/jchengai/forecast-mae#:~:text=MAE%2Dpretrained_weights%3A%20download.) along with a demo [notebook](https://github.com/jchengai/forecast-mae/blob/main/notebook/mae_reconstruction.ipynb).
