### ISSUE TITLE
The data

### ISSUE THREAD

**Issue by gankaia** [jchengai/forecast-mae#8]
Hey! I'm a beginner in the field of vehicle trajectory prediction, and I would like to ask if I can apply the code to a normal vehicle trajectory, which only contains attributes such as x and y, speed, and lacks elements such as maps.
Looking forward to your reply!

**Comment by jchengai** [comment]
Hi @kelen1, yes, for example, you can remove the `lane_feat` in the concatenation

https://github.com/jchengai/forecast-mae/blob/cb86ea92601d23a8af7713389e9fb78d7e546a65/src/model/model_forecast.py#L125

Besides, I believe there are several works focusing on map-free prediction (e.g., [CART-Pred](https://github.com/schmidt-ju/crat-pred)), and almost all prediction networks can be used for map-free prediction by just droping the map features.

**Comment by gankaia** [comment]
I get it. Thank you very much!

**Comment by kelen1** [comment]
Hey! I'm having trouble running the code.
After I delete the code related to lane, I try to run the preprocess.py, but I get an error, the detailed information is below.

0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]

I don't know what's wrong. Sincerely for your help.
