### ISSUE TITLE
An error when running 'train.py'

### ISSUE THREAD

**Issue by gankaia** [jchengai/forecast-mae#9]
Hey! When I try to run 'train.py', an error is reported, the detailed information is below:

Error executing job with overrides: ['data_root=/root/autodl-tmp/data_root', 'model=model_forecast', 'batch_size=16', 'monitor=val_minFDE'] Error locating target 'src.model.trainer_forecast.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception. full_key: model.target

I try to find the resaon, but no results. Had anyone had a similar issue? Sincerely for help. Thanks!

**Comment by kelen1** [comment]
Hey! When I try to run 'train.py', an error is reported, the detailed information is below:

Error executing job with overrides: ['data_root=/root/autodl-tmp/data_root', 'model=model_forecast', 'batch_size=16', 'monitor=val_minFDE'] Error locating target 'src.model.trainer_forecast.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception. full_key: model.target

I try to find the reason, but no results. Had anyone had a similar issue? Sincerely for help. Thanks!

**Comment by jchengai** [comment]
Hi @kelen1, can you paste your command that raises this error?

**Comment by gankaia** [comment]
The command is below:
root@autodl-container-a1e043b06b-1dc7b9a9:~/autodl-tmp# python3 train.py data_root=/root/autodl-tmp/data_root model=model_forecast batch_size=16 monitor=val_minFDE

The detailed error information is below:
/root/miniconda3/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Seed set to 2333
Trainer already configured with model summary callbacks: [<class 'pytorch_lightning.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
conf.model.target {'_target_': 'src.model.trainer_forecast.Trainer', 'dim': 128, 'historical_steps': 50, 'future_steps': 60, 'encoder_depth': 4, 'num_heads': 8, 'mlp_ratio': 4.0, 'qkv_bias': False, 'drop_path': 0.2, 'pretrained_weights': '${pretrained_weights}', 'lr': '${lr}', 'weight_decay': '${weight_decay}', 'epochs': '${epochs}', 'warmup_epochs': '${warmup_epochs}'}
Error executing job with overrides: ['data_root=/root/autodl-tmp/data_root', 'model=model_forecast', 'batch_size=16', 'monitor=val_minFDE']
Error locating target 'src.model.trainer_forecast.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.target

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by kelen1** [comment]
When I run the code, the initial strategy caused an error:
ValueError: You selected an invalid strategy name: `strategy=None`. It must be either a string or an instance of `pytorch_lightning.strategies.Strategy`. Example choices: auto, ddp, ddp_spawn, deepspeed, ... Find a complete list of options in our documentation at https://lightning.ai

So I changed the strategy to auto, and I'm not sure if this is the cause of error just now.

**Comment by jchengai** [comment]
I see, I'm investing in this issue.

**Comment by jchengai** [comment]
Hi @kelen1, I think the problem is that there are some other projects in your PYTHONPATH that have similar folder structure `project/src/model`. Can you check your PYTHONPATH by `echo $PYTHONPATH`?

**Comment by kelen1** [comment]
Hi, @jchengai .  It seems to be empty...

**Comment by gankaia** [comment]
Hi, @jchengai.  It seems to be empty...

**Comment by kelen1** [comment]
I want to know what the folder _'conf'_ does because it has a subfolder _'model'_ inside it, and I'm not sure if that's the reason for the previous error

**Comment by gankaia** [comment]
I downloaded the code and set the environment again, the problem seemed to be solved. Thanks!
